### ISSUE TITLE
Return an issue when a special program is played

### ISSUE THREAD

**Issue by mattberjon** [mattberjon/fip#2]
The program returns an issue when a special program is played.
```python
Title: Spéciales FIP
Traceback (most recent call last):
  File "/home/mattberjon/repo/fip/venv/bin/fip", line 9, in <module>
    load_entry_point('fip', 'console_scripts', 'fip')()
  File "/home/mattberjon/repo/fip/venv/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/mattberjon/repo/fip/venv/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/mattberjon/repo/fip/venv/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mattberjon/repo/fip/venv/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/mattberjon/repo/fip/fip/cli.py", line 63, in main
    display(data.data)
  File "/home/mattberjon/repo/fip/fip/cli.py", line 22, in display
    if data['authors']:
KeyError: 'authors'
```

**Comment by mattberjon** [comment]
In that case, it's necessary to check if the keys exist and maybe display a message to user asking if he wants to really save it (because sometimes no relevant information are given and it's useless to save it)
